version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    # For the dev database we usually want to reset the data every time we run the container. 
    # Uncomment this (and lines in "volumes.db" below) to persist data when restarting the container.
    # volumes:
    #   - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=user
      - POSTGRES_DB=authorization_db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  # Uncomment this to persist data when restarting the container.
  # db:
  #   driver: local
  pgadmin-data:
